---
extends: default
ignore: |
  **/secrets.sops.yaml
  charts/*/templates/
rules:
  line-length:
    max: 160
    level: warning
  document-start: disable
  truthy:
    check-keys: false
    level: warning
  indentation:
    indent-sequences: whatever
