{{- if not .Values.members }}{{ fail "members are required" }}{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-admin
  namespace: {{ required "namespace is required" .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  {{- range .Values.members }}
  - kind: User
    name: {{ required "member identity is required" .identity }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-{{ required "tenant is required" .Values.tenant }}-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  {{- range .Values.members }}
  - kind: User
    name: {{ required "member identity is required" .identity }}
  {{- end }}
